%%{init: {'flowchart': {'htmlLabels': true}}}%%
flowchart LR
    Start([SPC Corpus]) --> Ch3["<u><span style='color:#1a0dab;'>chapter_3.yaml<br/>Level 2 refinements</span></u>"]
    click Ch3 "./input/search_terms/chapter_3.yaml" "Open chapter_3.yaml"

    subgraph Chapter3Sets["Chapter 3 searches"]
        direction TB
        C3_1["Set 1:<br/>Protected/OECM + NBSAP + cases<br/>+ spatial prioritization + regional scales<br/>(n = <<C3_1>>)"]
        C3_3["Set 3:<br/>Restoration planning + connectivity + resilience<br/>(n = <<C3_3>>)"]
        C3_3.1A["Set 3.1 A:<br/>Objective<br/>(n = <<C3_3.1A>>)"]
        C3_3.1BCD["Set 3.1 BCD:<br/>Concept<br/>(n = <<C3_3.1BCD>>)"]
        C3_3.2D["Set 3.2 D:<br/>???<br/>(n = <<C3_3.2D>>)"]
        C3_3.2F["Set 3.2 F:<br/>???<br/>(n = <<C3_3.2F>>)"]
        C3_3.3["Set 3.3:<br/>???<br/>(n = <<C3_3.3>>)"]
        C3_4["Set 4:<br/>Systematic conservation planning / gap analysis<br/>(n = <<C3_4>>)"]
        C3_4.1AB["Set 4.1 AB:<br/>???<br/>(n = <<C3_4.1AB>>)"]
        C3_4.1CD["Set 4.1 CD:<br/>???<br/>(n = <<C3_4.1CD>>)"]
        C3_4.2["Set 4.2:<br/>???<br/>(n = <<C3_4.2>>)"]


        C3_5.1["Set 5.1:<br/>???<br/>(n = <<C3_5.1>>)"]
        C3_5.2["Set 5.1:<br/>???<br/>(n = <<C3_5.2>>)"]
    end
    Ch3 --> C3_1
    Ch3 --> C3_3
    Ch3 --> C3_3.1A
    Ch3 --> C3_3.1BCD
    Ch3 --> C3_3.2D
    Ch3 --> C3_3.2F
    Ch3 --> C3_3.3
    Ch3 --> C3_4
    Ch3 --> C3_4.1AB
    Ch3 --> C3_4.1CD
    Ch3 --> C3_4.2
    Ch3 --> C3_5.1
    Ch3 --> C3_5.2
